-- Initial Schema for WHMBiller

CREATE TABLE IF NOT EXISTS `settings` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `setting_key` VARCHAR(100) UNIQUE NOT NULL,
    `setting_value` TEXT
);

CREATE TABLE IF NOT EXISTS `roles` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(50) UNIQUE NOT NULL,
    `permissions` TEXT -- JSON list of permissions
);

CREATE TABLE IF NOT EXISTS `users` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `username` VARCHAR(50) UNIQUE NOT NULL,
    `email` VARCHAR(100) UNIQUE NOT NULL,
    `password` VARCHAR(255) NOT NULL,
    `role` ENUM('admin', 'staff', 'client', 'reseller') DEFAULT 'client',
    `role_id` INT, -- For granular staff roles
    `status` ENUM('active', 'suspended', 'pending') DEFAULT 'active',
    `two_factor_secret` VARCHAR(100),
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`role_id`) REFERENCES `roles`(`id`)
);

CREATE TABLE IF NOT EXISTS `login_logs` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `username` VARCHAR(50),
    `ip_address` VARCHAR(45),
    `status` ENUM('success', 'failed') NOT NULL,
    `attempt_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `ip_protection` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `ip_address` VARCHAR(45) UNIQUE NOT NULL,
    `status` ENUM('whitelist', 'blacklist', 'none') DEFAULT 'none',
    `failed_attempts` INT DEFAULT 0,
    `successful_sessions` INT DEFAULT 0,
    `block_until` TIMESTAMP NULL,
    `last_attempt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `country_protection` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `country_code` CHAR(2) UNIQUE NOT NULL,
    `country_name` VARCHAR(100) NOT NULL,
    `status` ENUM('whitelisted', 'blacklisted', 'not_specified') DEFAULT 'not_specified'
);

CREATE TABLE IF NOT EXISTS `products` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(100) NOT NULL,
    `description` TEXT,
    `price` DECIMAL(15, 2) NOT NULL,
    `recurring_period` ENUM('monthly', 'quarterly', 'semi_annually', 'annually', 'biennially', 'triennially') DEFAULT 'monthly',
    `type` VARCHAR(50) NOT NULL, -- e.g., 'hosting', 'domain', 'vps'
    `module_settings` TEXT, -- JSON settings for WHM/CloudLinux
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `servers` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(100) NOT NULL,
    `hostname` VARCHAR(255) NOT NULL,
    `ip_address` VARCHAR(45),
    `username` VARCHAR(50) NOT NULL,
    `api_token` TEXT NOT NULL,
    `type` VARCHAR(50) DEFAULT 'whm',
    `status` ENUM('active', 'disabled') DEFAULT 'active'
);

CREATE TABLE IF NOT EXISTS `user_services` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `user_id` INT NOT NULL,
    `product_id` INT NOT NULL,
    `server_id` INT,
    `domain` VARCHAR(255),
    `username` VARCHAR(50),
    `password` VARCHAR(255),
    `status` ENUM('active', 'suspended', 'terminated', 'pending') DEFAULT 'pending',
    `next_due_date` DATE,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`user_id`) REFERENCES `users`(`id`),
    FOREIGN KEY (`product_id`) REFERENCES `products`(`id`),
    FOREIGN KEY (`server_id`) REFERENCES `servers`(`id`)
);

CREATE TABLE IF NOT EXISTS `invoices` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `user_id` INT NOT NULL,
    `amount` DECIMAL(15, 2) NOT NULL,
    `currency` CHAR(3) DEFAULT 'NGN',
    `status` ENUM('unpaid', 'paid', 'cancelled', 'refunded') DEFAULT 'unpaid',
    `due_date` DATE NOT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`user_id`) REFERENCES `users`(`id`)
);

CREATE TABLE IF NOT EXISTS `reseller_settings` (
    `user_id` INT PRIMARY KEY,
    `wholesale_discount` DECIMAL(5, 2) DEFAULT 0.00, -- Percentage
    `retail_markup` DECIMAL(5, 2) DEFAULT 0.00, -- Percentage
    `custom_domain` VARCHAR(255),
    FOREIGN KEY (`user_id`) REFERENCES `users`(`id`)
);

CREATE TABLE IF NOT EXISTS `credit_transactions` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `user_id` INT NOT NULL,
    `amount` DECIMAL(15, 2) NOT NULL,
    `type` ENUM('add', 'deduct') NOT NULL,
    `description` TEXT,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`user_id`) REFERENCES `users`(`id`)
);

-- Default Settings
INSERT INTO `settings` (`setting_key`, `setting_value`) VALUES
('bf_max_user_failures', '5'),
('bf_max_ip_failures', '10'),
('bf_period', '15'),
('bf_lock_admin', '0'),
('bf_block_duration', '1 day'),
('smtp_port', '587'),
('base_currency', 'NGN'),
('secondary_currency', 'USD'),
('exchange_rate', '1500');

-- Countries List (Partial sample for brevity, in real app would be full)
INSERT INTO `country_protection` (`country_code`, `country_name`, `status`) VALUES
('AF', 'Afghanistan', 'not_specified'),
('AL', 'Albania', 'not_specified'),
('DZ', 'Algeria', 'not_specified'),
('AS', 'American Samoa', 'not_specified'),
('AD', 'Andorra', 'not_specified'),
('AO', 'Angola', 'not_specified'),
('AI', 'Anguilla', 'not_specified'),
('AQ', 'Antarctica', 'not_specified'),
('AG', 'Antigua and Barbuda', 'not_specified'),
('AR', 'Argentina', 'not_specified'),
('AM', 'Armenia', 'not_specified'),
('AW', 'Aruba', 'not_specified'),
('AU', 'Australia', 'not_specified'),
('AT', 'Austria', 'not_specified'),
('AZ', 'Azerbaijan', 'not_specified'),
('BS', 'Bahamas', 'not_specified'),
('BH', 'Bahrain', 'not_specified'),
('BD', 'Bangladesh', 'not_specified'),
('BB', 'Barbados', 'not_specified'),
('BY', 'Belarus', 'not_specified'),
('BE', 'Belgium', 'not_specified'),
('BZ', 'Belize', 'not_specified'),
('BJ', 'Benin', 'not_specified'),
('BM', 'Bermuda', 'not_specified'),
('BT', 'Bhutan', 'not_specified'),
('BO', 'Bolivia', 'not_specified'),
('BA', 'Bosnia and Herzegovina', 'not_specified'),
('BW', 'Botswana', 'not_specified'),
('BR', 'Brazil', 'not_specified'),
('BN', 'Brunei Darussalam', 'not_specified'),
('BG', 'Bulgaria', 'not_specified'),
('BF', 'Burkina Faso', 'not_specified'),
('BI', 'Burundi', 'not_specified'),
('KH', 'Cambodia', 'not_specified'),
('CM', 'Cameroon', 'not_specified'),
('CA', 'Canada', 'not_specified'),
('CV', 'Cape Verde', 'not_specified'),
('KY', 'Cayman Islands', 'not_specified'),
('CF', 'Central African Republic', 'not_specified'),
('TD', 'Chad', 'not_specified'),
('CL', 'Chile', 'not_specified'),
('CN', 'China', 'not_specified'),
('CO', 'Colombia', 'not_specified'),
('KM', 'Comoros', 'not_specified'),
('CG', 'Congo', 'not_specified'),
('CD', 'Congo, The Democratic Republic of the', 'not_specified'),
('CK', 'Cook Islands', 'not_specified'),
('CR', 'Costa Rica', 'not_specified'),
('CI', 'Cote D''Ivoire', 'not_specified'),
('HR', 'Croatia', 'not_specified'),
('CU', 'Cuba', 'not_specified'),
('CY', 'Cyprus', 'not_specified'),
('CZ', 'Czech Republic', 'not_specified'),
('DK', 'Denmark', 'not_specified'),
('DJ', 'Djibouti', 'not_specified'),
('DM', 'Dominica', 'not_specified'),
('DO', 'Dominican Republic', 'not_specified'),
('EC', 'Ecuador', 'not_specified'),
('EG', 'Egypt', 'not_specified'),
('SV', 'El Salvador', 'not_specified'),
('GQ', 'Equatorial Guinea', 'not_specified'),
('ER', 'Eritrea', 'not_specified'),
('EE', 'Estonia', 'not_specified'),
('ET', 'Ethiopia', 'not_specified'),
('FK', 'Falkland Islands (Malvinas)', 'not_specified'),
('FO', 'Faroe Islands', 'not_specified'),
('FJ', 'Fiji', 'not_specified'),
('FI', 'Finland', 'not_specified'),
('FR', 'France', 'not_specified'),
('GF', 'French Guiana', 'not_specified'),
('PF', 'French Polynesia', 'not_specified'),
('TF', 'French Southern Territories', 'not_specified'),
('GA', 'Gabon', 'not_specified'),
('GM', 'Gambia', 'not_specified'),
('GE', 'Georgia', 'not_specified'),
('DE', 'Germany', 'not_specified'),
('GH', 'Ghana', 'not_specified'),
('GI', 'Gibraltar', 'not_specified'),
('GR', 'Greece', 'not_specified'),
('GL', 'Greenland', 'not_specified'),
('GD', 'Grenada', 'not_specified'),
('GP', 'Guadeloupe', 'not_specified'),
('GU', 'Guam', 'not_specified'),
('GT', 'Guatemala', 'not_specified'),
('GN', 'Guinea', 'not_specified'),
('GW', 'Guinea-Bissau', 'not_specified'),
('GY', 'Guyana', 'not_specified'),
('HT', 'Haiti', 'not_specified'),
('HN', 'Honduras', 'not_specified'),
('HK', 'Hong Kong', 'not_specified'),
('HU', 'Hungary', 'not_specified'),
('IS', 'Iceland', 'not_specified'),
('IN', 'India', 'not_specified'),
('ID', 'Indonesia', 'not_specified'),
('IR', 'Iran, Islamic Republic of', 'not_specified'),
('IQ', 'Iraq', 'not_specified'),
('IE', 'Ireland', 'not_specified'),
('IL', 'Israel', 'not_specified'),
('IT', 'Italy', 'not_specified'),
('JM', 'Jamaica', 'not_specified'),
('JP', 'Japan', 'not_specified'),
('JO', 'Jordan', 'not_specified'),
('KZ', 'Kazakhstan', 'not_specified'),
('KE', 'Kenya', 'not_specified'),
('KI', 'Kiribati', 'not_specified'),
('KP', 'Korea, Democratic People''s Republic of', 'not_specified'),
('KR', 'Korea, Republic of', 'not_specified'),
('KW', 'Kuwait', 'not_specified'),
('KG', 'Kyrgyzstan', 'not_specified'),
('LA', 'Lao People''s Democratic Republic', 'not_specified'),
('LV', 'Latvia', 'not_specified'),
('LB', 'Lebanon', 'not_specified'),
('LS', 'Lesotho', 'not_specified'),
('LR', 'Liberia', 'not_specified'),
('LY', 'Libyan Arab Jamahiriya', 'not_specified'),
('LI', 'Liechtenstein', 'not_specified'),
('LT', 'Lithuania', 'not_specified'),
('LU', 'Luxembourg', 'not_specified'),
('MO', 'Macao', 'not_specified'),
('MK', 'Macedonia, The Former Yugoslav Republic of', 'not_specified'),
('MG', 'Madagascar', 'not_specified'),
('MW', 'Malawi', 'not_specified'),
('MY', 'Malaysia', 'not_specified'),
('MV', 'Maldives', 'not_specified'),
('ML', 'Mali', 'not_specified'),
('MT', 'Malta', 'not_specified'),
('MH', 'Marshall Islands', 'not_specified'),
('MQ', 'Martinique', 'not_specified'),
('MR', 'Mauritania', 'not_specified'),
('MU', 'Mauritius', 'not_specified'),
('YT', 'Mayotte', 'not_specified'),
('MX', 'Mexico', 'not_specified'),
('FM', 'Micronesia, Federated States of', 'not_specified'),
('MD', 'Moldova, Republic of', 'not_specified'),
('MC', 'Monaco', 'not_specified'),
('MN', 'Mongolia', 'not_specified'),
('MS', 'Montserrat', 'not_specified'),
('MA', 'Morocco', 'not_specified'),
('MZ', 'Mozambique', 'not_specified'),
('MM', 'Myanmar', 'not_specified'),
('NA', 'Namibia', 'not_specified'),
('NR', 'Nauru', 'not_specified'),
('NP', 'Nepal', 'not_specified'),
('NL', 'Netherlands', 'not_specified'),
('AN', 'Netherlands Antilles', 'not_specified'),
('NC', 'New Caledonia', 'not_specified'),
('NZ', 'New Zealand', 'not_specified'),
('NI', 'Nicaragua', 'not_specified'),
('NE', 'Niger', 'not_specified'),
('NG', 'Nigeria', 'not_specified'),
('NU', 'Niue', 'not_specified'),
('NF', 'Norfolk Island', 'not_specified'),
('MP', 'Northern Mariana Islands', 'not_specified'),
('NO', 'Norway', 'not_specified'),
('OM', 'Oman', 'not_specified'),
('PK', 'Pakistan', 'not_specified'),
('PW', 'Palau', 'not_specified'),
('PS', 'Palestinian Territory, Occupied', 'not_specified'),
('PA', 'Panama', 'not_specified'),
('PG', 'Papua New Guinea', 'not_specified'),
('PY', 'Paraguay', 'not_specified'),
('PE', 'Peru', 'not_specified'),
('PH', 'Philippines', 'not_specified'),
('PN', 'Pitcairn', 'not_specified'),
('PL', 'Poland', 'not_specified'),
('PT', 'Portugal', 'not_specified'),
('PR', 'Puerto Rico', 'not_specified'),
('QA', 'Qatar', 'not_specified'),
('RE', 'Reunion', 'not_specified'),
('RO', 'Romania', 'not_specified'),
('RU', 'Russian Federation', 'not_specified'),
('RW', 'Rwanda', 'not_specified'),
('SH', 'Saint Helena', 'not_specified'),
('KN', 'Saint Kitts and Nevis', 'not_specified'),
('LC', 'Saint Lucia', 'not_specified'),
('PM', 'Saint Pierre and Miquelon', 'not_specified'),
('VC', 'Saint Vincent and the Grenadines', 'not_specified'),
('WS', 'Samoa', 'not_specified'),
('SM', 'San Marino', 'not_specified'),
('ST', 'Sao Tome and Principe', 'not_specified'),
('SA', 'Saudi Arabia', 'not_specified'),
('SN', 'Senegal', 'not_specified'),
('CS', 'Serbia and Montenegro', 'not_specified'),
('SC', 'Seychelles', 'not_specified'),
('SL', 'Sierra Leone', 'not_specified'),
('SG', 'Singapore', 'not_specified'),
('SK', 'Slovakia', 'not_specified'),
('SI', 'Slovenia', 'not_specified'),
('SB', 'Solomon Islands', 'not_specified'),
('SO', 'Somalia', 'not_specified'),
('ZA', 'South Africa', 'not_specified'),
('GS', 'South Georgia and the South Sandwich Islands', 'not_specified'),
('ES', 'Spain', 'not_specified'),
('LK', 'Sri Lanka', 'not_specified'),
('SD', 'Sudan', 'not_specified'),
('SR', 'Suriname', 'not_specified'),
('SJ', 'Svalbard and Jan Mayen', 'not_specified'),
('SZ', 'Swaziland', 'not_specified'),
('SE', 'Sweden', 'not_specified'),
('CH', 'Switzerland', 'not_specified'),
('SY', 'Syrian Arab Republic', 'not_specified'),
('TW', 'Taiwan, Province of China', 'not_specified'),
('TJ', 'Tajikistan', 'not_specified'),
('TZ', 'Tanzania, United Republic of', 'not_specified'),
('TH', 'Thailand', 'not_specified'),
('TL', 'Timor-Leste', 'not_specified'),
('TG', 'Togo', 'not_specified'),
('TK', 'Tokelau', 'not_specified'),
('TO', 'Tonga', 'not_specified'),
('TT', 'Trinidad and Tobago', 'not_specified'),
('TN', 'Tunisia', 'not_specified'),
('TR', 'Turkey', 'not_specified'),
('TM', 'Turkmenistan', 'not_specified'),
('TC', 'Turks and Caicos Islands', 'not_specified'),
('TV', 'Tuvalu', 'not_specified'),
('UG', 'Uganda', 'not_specified'),
('UA', 'Ukraine', 'not_specified'),
('AE', 'United Arab Emirates', 'not_specified'),
('GB', 'United Kingdom', 'not_specified'),
('US', 'United States', 'not_specified'),
('UM', 'United States Minor Outlying Islands', 'not_specified'),
('UY', 'Uruguay', 'not_specified'),
('UZ', 'Uzbekistan', 'not_specified'),
('VU', 'Vanuatu', 'not_specified'),
('VE', 'Venezuela', 'not_specified'),
('VN', 'Viet Nam', 'not_specified'),
('VG', 'Virgin Islands, British', 'not_specified'),
('VI', 'Virgin Islands, U.S.', 'not_specified'),
('WF', 'Wallis and Futuna', 'not_specified'),
('EH', 'Western Sahara', 'not_specified'),
('YE', 'Yemen', 'not_specified'),
('ZM', 'Zambia', 'not_specified'),
('ZW', 'Zimbabwe', 'not_specified');
